"""First migrate

Revision ID: 797c02e5fb9f
Revises: 25ae6f2901f3
Create Date: 2022-01-06 18:28:48.615348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797c02e5fb9f'
down_revision = '25ae6f2901f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=20), nullable=False),
    sa.Column('lastname', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=40), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car', sa.String(length=20), nullable=False),
    sa.Column('from_date', sa.String(length=20), nullable=False),
    sa.Column('to_date', sa.String(length=20), nullable=False),
    sa.Column('booked_status', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_car_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_car'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    op.drop_table('user')
    # ### end Alembic commands ###
