"""pizdets

Revision ID: c54bb95bc516
Revises: 
Create Date: 2022-01-08 21:43:09.784453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54bb95bc516'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacture', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=20), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_car'))
    )
    op.create_table('user_car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car', sa.String(length=20), nullable=False),
    sa.Column('from_date', sa.String(length=20), nullable=False),
    sa.Column('to_date', sa.String(length=20), nullable=False),
    sa.Column('booked_status', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_user_car_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_car'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_car')
    op.drop_table('car')
    # ### end Alembic commands ###
